#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd

      echo "2" > /sys/class/misc/boeffla_sound/eq
      
case "$eq_selection" in
  0)
    echo "0 0 0 0 0" > /sys/class/misc/boeffla_sound/eq_gains
    echo "0" > /sys/class/misc/boeffla_sound/eq
    ;;
  1)

case "$eq_preset" in
  0)
    echo "0 0 0 0 0" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  1)
    echo "12 5 3 -1 1" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  2)
    echo "10 2 0 2 5" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  3)
    echo "-5 1 0 4 3" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  4)
    echo "0 0 0 -3 -5" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  5)
    echo "8 2 -2 3 8" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  6)
    echo "12 2 4 2 3" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
  7)
    echo "10 -2 -2 3 10" > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
    ;;
esac;
;;
  2)

case "$eq_preset" in
  0)
    echo "0 0 0 0 0" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  1)
    echo "12 5 3 -1 1" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  2)
    echo "10 2 0 2 5" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  3)
    echo "-5 1 0 4 3" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  4)
    echo "0 0 0 -3 -5" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  5)
    echo "8 2 -2 3 8" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  6)
    echo "12 2 4 2 3" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
  7)
    echo "10 -2 -2 3 10" > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
    ;;
esac;
;;
  3)
    echo $eq_band1 " " $eq_band2 " " $eq_band3 " " $eq_band4 " " $eq_band5  > /sys/class/misc/boeffla_sound/eq_gains
    echo "1" > /sys/class/misc/boeffla_sound/eq
;;
  4)
    echo $eq_band1 " " $eq_band2 " " $eq_band3 " " $eq_band4 " " $eq_band5  > /sys/class/misc/boeffla_sound/eq_gains
    echo "2" > /sys/class/misc/boeffla_sound/eq
;;

esac;

fi
fi
